### ISSUE TITLE
Erreur  : impossible de se connecter (ce soir)

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#889] opened 2019-12-18 18:48 UTC
Error log 
crashed

File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\gui\trio_thread.py", line 98, in _run_fn
result = await self._fn(*self._args, **self._kwargs)

File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\gui\instance_widget.py", line 35, in _do_run_core
await core.mountpoint_manager.mount_all()

File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\mountpoint\manager.py", line 205, in mount_all
await self.mount_workspace(workspace_entry.id, timestamp=timestamp)

File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\mountpoint\manager.py", line 165, in mount_workspace
runner_task = await self._mount_workspace_helper(workspace)

File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\mountpoint\manager.py", line 139, in _mount_workspace_helper
runner_task = await start_task(self._nursery, curried_runner)

File "C:\Program Files (x86)\Parsec\site-packages\parsec\utils.py", line 92, in start_task
return await nursery.start(TaskStatus.wrap_task, corofn, *args, name=name)

File "C:\Program Files (x86)\Parsec\site-packages\parsec\service_nursery.py", line 183, in start
return await type(nursery).start(nursery, wrap_child, name=name or async_fn)

File "C:\Program Files (x86)\Parsec\site-packages\trio\_core\_run.py", line 952, in start
old_nursery.start_soon(thunk, *args, name=name)

File "C:\Program Files (x86)\Parsec\site-packages\trio\_core\_run.py", line 730, in __aexit__
raise combined_error_from_nursery

File "C:\Program Files (x86)\Parsec\site-packages\parsec\service_nursery.py", line 181, in wrap_child
await async_fn(*args, task_status=task_status)

File "C:\Program Files (x86)\Parsec\site-packages\parsec\utils.py", line 79, in wrap_task
value = await nursery.start(corofn, *args)

File "C:\Program Files (x86)\Parsec\site-packages\parsec\service_nursery.py", line 183, in start
return await type(nursery).start(nursery, wrap_child, name=name or async_fn)

File "C:\Program Files (x86)\Parsec\site-packages\trio\_core\_run.py", line 952, in start
old_nursery.start_soon(thunk, *args, name=name)

File "C:\Program Files (x86)\Parsec\site-packages\trio\_core\_run.py", line 730, in __aexit__
raise combined_error_from_nursery

File "C:\Program Files (x86)\Parsec\site-packages\parsec\service_nursery.py", line 181, in wrap_child
await async_fn(*args, task_status=task_status)

File "C:\Program Files (x86)\Parsec\site-packages\parsec\core\mountpoint\winfsp_runner.py", line 124, in winfsp_mountpoint_runner
raise MountpointDriverCrash(f"WinFSP has crashed on {mountpoint_path}: {exc}") from exc

**Comment by PhClermontScille** [comment] 2019-12-19 11:53
Le problème vient de crash du PC Windows 10 et de la non suppression des 4 sous-dossiers de Parsec_mnt
![image](https://user-images.githubusercontent.com/13103240/71171591-739a8c80-225e-11ea-9ab3-e8b40d6dd03c.png)

La suppression des ces 4 dossiers, non disparus suite à crash avec Parsec connecté, resoud le problème.
Ceci dit, les crash se produiront chez les clients. **Quand on lance le client PARSEC, il faudra vérifier si il n'y a pas des scories suite à crash et les supprimer.**

**Comment by vxgmichel** [comment] 2019-12-19 11:59
Merci pour le rapport de bug @PhClermontScille, je travaille dessus.

Duplicate of #881.

**Closed by vxgmichel** 2019-12-19 11:59 UTC
