### ISSUE TITLE
Warning window relatively to Acrobate Reader DC bug

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#1082] opened 2020-04-01 16:50 UTC
Feed back of a novice user april the 1st 2020 : "_People generaly hates that a software changes the default settings. The warning window relatively to Acrobate Reader DC's bug  is unnecessarily anxiety-provoking, user place before a choice of which he does not control the causes and the consequences._"
![image](https://user-images.githubusercontent.com/9845177/78163776-1f9c6800-7449-11ea-9849-ef222039f90a.png)

The previous message is not understandable for an npovice user and should be modified as follow :
In english :
> By default, the Acrobate Reader DC software presents an uncorrected bug (reference of the bug) which prohibits the opening of a PDF file directly in a Parsec enclave. We suggest that you fix this bug.
> If you do not correct this bug, you will still be able to use Parsec, but you will not be able to execute a PDF file on Acrobate Reader DC directly from a Parsec enclave. The solution will then be:
> - either download the files locally before launching them
> - or to install another PDF reader which does not present this bug, like Sumatra

In french :
> Par défaut, le logiciel Acrobate Reader DC présente un bug non corrigé (référence du bug) qui interdit l'ouverture d'un fichier PDF directement dans une enclave Parsec. Nous vous proposons de corriger ce bug.
> Si vous ne corrigez pas ce bug, vous pourrez toujours utiliser Parsec, mais vous ne pourrez pas exécuter un fichier PDF sur Acrobate Reader DC directement depuis une enclave Parsec. La solution sera alors  :
> - soit de télécharger les fichiers en local avant de les lancer 
> - soit d'installer un autre lecteur de PDF qui ne présente pas ce bug, comme Sumatra

The choice button must be :
- Oui, rendre compatible / Yes, make compatible
- Non / No

**Comment by Max-7** [comment] 2020-04-03 09:51
The message is meant to be anxiety-inducing. Adobe containers are a security feature, not a bug. The bug is only that they don't work well with Parsec mountpoints and the only solution we found is to disable them, but it is not something that should be done lightly. We could improve the message, explaining what containers are and why they don't work well with Parsec (thought it could become too technical), but absolutely not by presenting them as a bug we could fix for the user.

**Comment by vxgmichel** [comment] 2020-06-03 17:52
Outdated after #1159

**Comment by touilleMan** [comment] 2020-06-04 13:43
Will be fixed by #1159

**Closed by touilleMan** 2020-06-04 13:43 UTC
Labels: enhancement, feedback, gui, low
