### ISSUE TITLE
Upgrade system for Electron

### ISSUE THREAD

**Issue by NicoTuxx** [Scille/parsec-cloud#3901] opened 2023-01-13 13:16 UTC
- how to upgrade with Electron (out of the box)
- how to change system and maintain continuity with existing system

**Comment by Max-7** [comment] 2023-07-25 12:05
Auto-updating the electron app should not be too much of a problem, everything seems to be handled automatically with https://www.electronjs.org/docs/latest/tutorial/tutorial-publishing-updating just by publishing new versions as Github releases.

**Comment by FirelightFlagboy** [comment] 2023-10-23 14:47
Duplicate of #5613

**Closed by FirelightFlagboy** 2023-10-23 14:47 UTC
