### ISSUE TITLE
[🐛 | Bug]: Redirect server response not managed

### ISSUE THREAD

**Issue by Landeers** [Scille/parsec-cloud#8574] opened 2024-10-01 15:02 UTC
### Parsec version tested on:

3.0.1

### Platforms tested on:

Windows

### Bug description:

When Parsec client receives a http response code 301 or 302 (ex : redirect to https), it does nothing instead of resend request to the redirect url.

Full exemple :
- Parsec server is behind a reverse proxy. Parsec doesn't have certificate
- the reverse proxy manage it's own certificat and redirect all http request to https
- REST request to create a new organization is OK (https://domain/administration/organizations)
- Parsec server return a bootstrap link parsec3://domain/organization?no_ssl=true&a=...&p=....
- When using this link to join organization, reverse proxy return a redirection code (301 or 302) to switch http to https. Http orignal request comes from no_ssl=true
- Parsec client do nothing more... So redirected url is never used, and organization is not bootstraped.

**Comment by FirelightFlagboy** [comment] 2024-10-02 12:19
Should be fixed by settings

```
# Enforce HTTPS by redirecting HTTP request.
PARSEC_FORWARD_PROTO_ENFORCE_HTTPS=X-Forwarded-Proto:https
```

**Comment by FirelightFlagboy** [comment] 2024-10-04 13:47
Superseded by #8626, the problem is that the server is behind a proxy and it would be better to handle the forwarded header when enabled in the configuration

**Closed by FirelightFlagboy** 2024-10-04 13:47 UTC
Labels: C-Bug, A-Client
