### ISSUE TITLE
Show mountpoint in Wirdows Explorer left panel not working

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#674] opened 2019-09-11 13:56 UTC
option enabled:
![image](https://user-images.githubusercontent.com/3187637/64703314-7a21a700-d4ac-11e9-97fb-639877a4e16f.png)

But nothing in the explorer:
![image](https://user-images.githubusercontent.com/3187637/64703361-8c034a00-d4ac-11e9-9680-2088efeab99f.png)

I've tried to restart the client (and disable the option, restart, then reenable&restart) with no change.
No error logs.

**Comment by touilleMan** [comment] 2019-09-11 14:00
Could it be because because Parsec is not installed (I working with the repo version) ?
If so, is there something we could do ?

**Comment by Max-7** [comment] 2019-12-16 08:12
Duplicate of #839, closing this one.

**Closed by Max-7** 2019-12-16 08:12 UTC
Labels: bug, gui
