### ISSUE TITLE
Sharing a workspace with a revoked user

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#334] opened 2019-03-21 04:43 UTC
When a user have been revoked, it is still possible to force the sharing of a workspace by writing the full name, even if it does not appear in the list of users. It must be IMPOSSIBLE to share a workspace with a revoked user.

**Comment by Max-7** [comment] 2019-03-22 10:22
Duplicate of #220. Closing this one.

**Closed by Max-7** 2019-03-22 10:22 UTC
Labels: enhancement, medium
