### ISSUE TITLE
File history window contains redundant entries (ubuntu client)

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#766] opened 2019-10-30 11:02 UTC
Steps to reproduce :
1. Upload a file in the workspace.
2. After some time (10 min) check the history of the file.
3. There are 3 entries in the history - there is no clear understanding of why there are three. In my opinion there should be only one, the file has not been modified...
(picture attached)

![image](https://user-images.githubusercontent.com/8625772/67851658-2d9d3400-fb0b-11e9-9987-1f06e67196fd.png)

**Comment by c4ffein** [comment] 2019-11-04 14:38
Some redundant entries are the result of the modifications of parent manifests, this will be fixed soon. For the entry with size 0, I thought this was more problematic, and had the confirmation from @touilleMan : the problem is that the manifests actually don't allow us to make the difference between one that is really empty, and one that is only a mocked version needed before updating the parent. So this one can't be fixed easily for now without risking to loose some information, as we either ignore version 0 that is sometimes needed, or have to update the manifests structure : this will be done in another PR

**Closed** 2019-11-08 18:41 UTC
Labels: enhancement, gui, v1 - official release
