### ISSUE TITLE
[🚀 | Feature request]: Share Workspace with multiple users at once

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#8539] opened 2024-09-27 14:43 UTC
### What you would like to accomplish

If I want to share a workspace with multiple users, I need to add them and select their role, one by one.

I would like to be able to share a workspace with multiple users at once. 

### How the feature should work

Changes to the Share this workspace dialog

- Display a checkbox next to each user
- When a user is checked, a combo appears (e.g. somewhere on top) to select a role
- When applied, the selected role will be applied to all checked users
- There should be an option to check "All" or "None"

**Comment by FirelightFlagboy** [comment] 2024-10-02 12:06
Duplicate of #8326

**Closed by FirelightFlagboy** 2024-10-02 12:06 UTC
Labels: B-Triage, C-Feature-Request
