### ISSUE TITLE
Crash when opening file: AssertionError _ensure_hot_file

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#319] opened 2019-03-18 16:45 UTC
![image](https://user-images.githubusercontent.com/3187637/54547234-a4832380-49a5-11e9-9f15-f446b5f5531c.png)

**Comment by frossigneux** [comment] 2019-03-20 13:59
Duplicate of https://github.com/Scille/parsec-cloud/issues/303?
Seems to be fixed, probably by https://github.com/Scille/parsec-cloud/pull/328

**Closed by frossigneux** 2019-03-20 13:59 UTC
Labels: bug, high, mountpoint, windows
