### ISSUE TITLE
ouverture Pdf

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#860] opened 2019-12-05 18:43 UTC
impossibilite d'ouverture de pdf
![Capture d'écran 2019-12-05 19 37 39](https://user-images.githubusercontent.com/46708918/70263793-7180fa00-1797-11ea-850f-af9f06791516.png)

**Comment by Max-7** [comment] 2019-12-06 08:53
Duplicate of #840, closing this one.

**Closed by Max-7** 2019-12-06 08:53 UTC
