### ISSUE TITLE
Invitation window doesn't always pop up if Parsec isn't already open

### ISSUE THREAD

**Issue by Ironicbay** [Scille/parsec-cloud#1859] opened 2021-09-17 08:43 UTC

**Comment by Max-7** [comment] 2021-10-04 07:37
Could not reproduce on Windows.

**Comment by mmmarcos** [comment] 2024-01-11 10:08
Closing as not reproducible. We'll open a new issue if this is present on the V3 branch.

**Closed by mmmarcos** 2024-01-11 10:08 UTC
Labels: A-MacOS
