### ISSUE TITLE
[🐛 | Bug]: Crash on "Click to enlarge" QR code

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#4369] opened 2023-04-03 09:29 UTC
### Version

2.15.1-rc1

### What platforms you were running our software when the bug happened ?

Linux

### What happened ?

Steps to reproduce:

1. Open `My devices`
2. Click on `Invite a new device`
3. On the `Add a new device` dialog, click on the QR code to enlarge it
4. Click on the image to close
5. Click again to enlarge the QR code
6. :boom: CRASH

Edit: Crash also happens on step 3 if the mouse pointer is moved in and out the image.

### Relevant output

On first click on the image (step 3):
```shell
2023-04-03T09:33:21.866680Z [error    ] Exception in Qt slot           
Traceback (most recent call last):
  File "/snap/parsec/254/site-packages/parsec/core/gui/custom_widgets.py", line 315, in enterEvent
    self._draw_overlay()
  File "/snap/parsec/254/site-packages/parsec/core/gui/custom_widgets.py", line 349, in _draw_overlay
    if icon_scaled:
UnboundLocalError: local variable 'icon_scaled' referenced before assignment
```
On crash (step 5/6):
```shell
QPaintDevice: Cannot destroy paint device that is being painted
[1]    33625 segmentation fault  snap run parsec
```

**Comment by FirelightFlagboy** [comment] 2023-04-03 14:43
Duplicate of #3769 already fixed

**Closed by FirelightFlagboy** 2023-04-03 14:43 UTC
Labels: bug, python
