### ISSUE TITLE
Signal the synchronization progress to the user

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#1002] opened 2020-02-26 13:49 UTC
Currently, when users open a large file they don't have an indication that Parsec is downloading the file in the background. If the file is large and download takes long, they are tempted to double click again or to abandon, thinking that nothing is happening.

We need to signal (by pop-up? sys tray? icon change) that Parsec is syncrhonizing the file.

**Comment by touilleMan** [comment] 2020-02-26 13:54
duplicate of #694

**Closed by touilleMan** 2020-02-26 13:54 UTC
Labels: enhancement, gui, high
