### ISSUE TITLE
Potential file corruption issue

### ISSUE THREAD

**Issue by Max-7** [Scille/parsec-cloud#445] opened 2019-05-10 14:24 UTC
![image](https://user-images.githubusercontent.com/18075498/57534357-25282580-7340-11e9-8ac0-addbf2746eea.png)

**Comment by Max-7** [comment] 2019-05-10 14:33
Only seems to happen with PDF.

**Comment by Max-7** [comment] 2019-05-10 16:59
Happens on a few files that seems to be corrupted (checksum before/after importing in Parsec differ).

**Comment by vxgmichel** [comment] 2020-02-14 14:25
Duplicate of #878

**Closed by vxgmichel** 2020-02-14 14:25 UTC
Labels: bug, mountpoint, windows
