### ISSUE TITLE
Avoid updating access timestamp in DB when doing a chunk read

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#4061] opened 2023-02-14 15:25 UTC
https://github.com/Scille/parsec-cloud/blob/2ac925b4757fbfb88b22128c232a01e283297a9c/parsec/core/fs/storage/chunk_storage.py#L145-L151

Having to do a write every time we read a chunk has most likely a performance cost.

So it would be interesting compare the performances with a tweaked version of the code where only read is done (i.e. the update timestamp logic is disabled)

My guess is, on top of the obvious "read operations faster than write ones" rule, that we will be able in the long run (some architecture has to be changed for that...) to do concurrent read operations on the database (where write only allow a single operation at a given time).

**Comment by FirelightFlagboy** [comment] 2023-09-01 10:05
Duplicate of #5009

**Closed by FirelightFlagboy** 2023-09-01 10:05 UTC
