### ISSUE TITLE
Alerte sécurité Norton Antivirus : Parsec Windows 32 bits

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#1049] opened 2020-03-23 20:30 UTC
Première installation sur un pc W10 32 bits : 
![image](https://user-images.githubusercontent.com/13103240/77360355-7f11be00-6d4d-11ea-8c39-be380815dd35.png)

**Comment by touilleMan** [comment] 2020-03-25 13:47
duplicate of #1050

**Closed by touilleMan** 2020-03-25 13:47 UTC
Labels: windows

**Comment by c4ffein** [comment] 2020-03-26 11:00
Actually not a duplicate, but we got an alert on Norton because our product isn't used enough with this AV yet, our code is signed with an EV certificate, but that only covers Microsoft Smartscreen validation, and contrarily to most AV, Norton doesn't provide a program to whitelist executables (e.g. Avast does, and that helped us past the verification some versions ago)
So still closed as there is not much we can do.

**Comment by PhClermontScille** [comment] 2020-03-26 12:18
Puis mais ce problème n'existe pas avec la version 64bits de PARSEC. Il
existait au début. Maintenant : "parsec est sécurisé ".
